driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.6
  - name: freebsd-10.3
  - name: freebsd-11.0
  - name: fedora-25
  - name: opensuse-leap-42.2
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: windows-2012r2-standard
    driver:
      box: chef/windows-server-2012r2-standard # private box in Chef's Atlas account
  - name: windows-2008r2-standard
    driver:
      box: chef/windows-server-2008r2-standard # private box in Chef's Atlas account
  - name: macosx-10.11
    driver:
      box: chef/macosx-10.11 # private box in Chef's Atlas account
      provider: vmware_fusion

suites:
- name: resources
  run_list:
  - recipe[test::default]
- name: source
  run_list:
  - recipe[test::source]
  excludes:
    - windows-2012r2-standard
    - windows-2008r2-standard
    - macosx-10.11
- name: server
  run_list:
  - recipe[test::server]
  excludes:
    - windows-2012r2-standard
    - windows-2008r2-standard
    - macosx-10.11
