name              'git'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs git and/or sets up a Git server daemon'
version           '10.1.0'
source_url        'https://github.com/sous-chefs/git'
issues_url        'https://github.com/sous-chefs/git/issues'
chef_version      '>= 14'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'freebsd'
supports 'mac_os_x'
supports 'omnios'
supports 'opensuseleap'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'smartos'
supports 'suse'
supports 'ubuntu'
supports 'windows'
